#!/bin/bash
set -euo pipefail

# installs git and make
# used for the initial run when neither git or make are available
# usage: curl me:
# curl https://example.com/dotfiles/init | bash /dev/stdin https://example.com/dotfiles

dotfiles_uri=$1
target_path=${2:-dotfiles}

apt update
apt upgrade -y
apt install -y sudo make git

[ -d $target_path ] || git clone $dotfiles_uri $target_path
cd $target_path
make
