inoremap ii <ESC>
" also remapped delete key on kinesis advantage to escape, 
" but this is more uniform


nnoremap <SPACE> <Nop>
let mapleader = "\<space>" 

nmap Y y$

nmap h <PageUp>
nmap l <PageDown>
nmap <Leader>q :qa<cr>
nmap <Leader>a :e #<cr>

map z<LeftMouse> :grep <c-r>=shellescape(expand("<cword>"))<cr><cr>
nmap <bs><LeftMouse> :cnext<cr>
nmap <bs><RightMouse> :cprev<cr>

nmap ]q :cnext<cr>
nmap [q :cprev<cr>

nmap ]w :lnext<cr>
nmap [w :lprev<cr>

map <X1Mouse> <C-O>
map <X2Mouse> <C-I>


nmap <bs>e :Make!<cr>
nmap <bs>i :Termdebug<cr>

let g:pandoc#formatting#mode = 'hA'

" navigate files and buffers
map <Leader>o :Files<Cr>
map <Leader>b :History<Cr>
set runtimepath^=~/.fzf

imap <c-f> <c-x><c-f>
imap <c-l> <c-x><c-l>

" use fzf variants to provide these completion kinds
imap <c-x><c-f> <plug>(fzf-complete-path)
imap <c-x><c-l> <plug>(fzf-complete-line)

" use `grepprg` with fzf

" interactive fzf variant
" map g/ :Grep<cr>

command! -bang -nargs=* Grep
  \ call fzf#vim#grep(
  \  &grepprg.' '.shellescape(<q-args>), 1,
  \   <bang>0 ? fzf#vim#with_preview('up:60%')
  \           : fzf#vim#with_preview('right:50%:hidden', '?'),
  \   <bang>0)


" searching and grepping
if executable('rg')
	" make :grep and :psearch use ripgrep
	set grepprg=rg\ --vimgrep
	
	" make file:line:col: be recognized so that when it 
	" you can jump right to the column from the quickfix 
	" list
	set grepformat+=%f:%l:%c:%m
	" TODO hard-set grep format to only this instead?
	" reinserts the less specific versions after this, 
	" otherwise they get used instead
	set grepformat-=%f:%l:%m
	set grepformat+=%f:%l:%m
	set grepformat-=%f:%l%m
	set grepformat+=%f:%l%m

	function! FindSymbol()
		:cexpr system("rg --fixed-strings --vimgrep " . shellescape(expand("<cword>")))
	endfunction
else
	set grepprg=grep\ -Hnr\ --exclude-dir=.git
	function! FindSymbol()
		:cexpr system("grep -F -n " . shellescape(expand("<cword>")))
	endfunction
endif

" find symbol under cursor
map <leader>s :call FindSymbol()<cr>

" global search
map g/ :grep<space>

" ignore vcs dirs when expanding wildcards.
set wildignore+=*/.git/*
" ignore tags files
set wildignore+=tags

set mouse=a
set nocompatible
set encoding=utf8
" get vim to remember undo history across file closes. 
set undofile
" TODO add prerequisite:
" !mkdir -p $HOME/.cache/vim/undo
set undodir=$HOME/.cache/vim/undo
set noswapfile
" set expandtab
" set tabstop=4
set autoindent
set autowriteall
set autoread
set backspace=indent,eol,start
set completeopt=menu,menuone
" only show any additional information such as attached docs in the preview window and only if it 
" is already open
set completeopt+=preview
set incsearch
set hlsearch
set ignorecase
set ruler
set noshowmode " don't show -- INSERT -- on the last line when in insert mode
set isfname-=: " make file linenumber , e.g.: file.c:32 work with gF on windows
set wildmenu
set clipboard^=unnamed
set clipboard^=unnamedplus
set splitbelow " open new splits below the current one instead of above
set splitright " open new splits to the right instead of to the left
" set number
" set relativenumber
set tw=60 " good fit on 29" screen
" setting formatting options, see `:h fo-table` for details on each flag
" enable formatting of comments with gq
set  formatoptions=q
" enable autoformatting
"set formatoptions+=a
" autoformatting of text, applies to "
" anything that is not-comments, such as code. if set here, 
" need to unset it in filetype specific config for code.
" set formatoptions+=t
" autoformatting of comments
set formatoptions+=c
" insert comment leader at start of line while writing a 
" comment in insert mode
set formatoptions+=r
" insert comment leader at start of line while on a comment 
" in normal mode and hitting o/O
set formatoptions+=o
" only join line if it ends with a space
set formatoptions+=w
" remove comment leader when joining lines
set formatoptions+=j
" don't add two spaces between sentences when joininglines
set nojoinspaces
" format numbered lists when formatting text
set formatoptions+=n
" don't break long lines when in insert mode. this relaxes 
" autoformatting which is useful in some cases. if the line 
" started as a long line, it will remain a long line.
set formatoptions+=l
" set scrolloff=4
set scrolloff=0
set shell=/bin/bash
let $BASH_ENV = "~/.bash_aliases"

" set shiftwidth=4 
" set softtabstop=4
set bg=dark
let g:tex_flavor='latex'
let g:Tex_ViewRule_pdf='zathura'
let g:Tex_DefaultTargetFormat='pdf'
" quiet a warning when putting an opening brace on it's own line, from https://github.com/vim-syntastic/syntastic/issues/2169
let g:syntastic_tex_lacheck_quiet_messages = { 'regex': '\Vpossible unwanted space at' }

" remove top banner
" let g:netrw_banner = 0
" expandable tree file listing 
let g:netrw_liststyle=3
" netrw window height when split
let g:netrw_winsize=30

let g:pathogen_disabled = ['syntastic', 'vim-pandoc', 'coc.nvim', 'YouCompleteMe', 'AutoComplPop',]


" 2023-12-20: disable eclim to get the :History command from 
let g:EclimDisabled = 1
call remove(g:pathogen_disabled, index(g:pathogen_disabled, 'syntastic'))

" messes with the autocompletion
call add(g:pathogen_disabled, 'supertab')

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0


if exists('g:vscode')
	" 2023-08-05 temporarily disable most plugins to speed up 
	" vscode-neovim
	call add(g:pathogen_disabled, 'ack.vim')
	call add(g:pathogen_disabled, 'autoclose')
	call add(g:pathogen_disabled, 'AutoComplPop')
	call add(g:pathogen_disabled, 'braceless.vim')
	call add(g:pathogen_disabled, 'clips.vim')
	call add(g:pathogen_disabled, 'coc.nvim')
	call add(g:pathogen_disabled, 'coquille')
	call add(g:pathogen_disabled, 'cscope')
	call add(g:pathogen_disabled, 'ctrlp.vim')
	call add(g:pathogen_disabled, 'dbext.vim')
	call add(g:pathogen_disabled, 'fzf.vim')
	call add(g:pathogen_disabled, 'goyo.vim')
	call add(g:pathogen_disabled, 'gundo')
	call add(g:pathogen_disabled, 'jedi-vim')
	call add(g:pathogen_disabled, 'limelight.vim')
	call add(g:pathogen_disabled, 'ocp-indent-vim')
	call add(g:pathogen_disabled, 'rainbowParanthesis')
	call add(g:pathogen_disabled, 'scmindent.rkt')
	call add(g:pathogen_disabled, 'slimv')
	call add(g:pathogen_disabled, 'supertab')
	call add(g:pathogen_disabled, 'syntastic')
	call add(g:pathogen_disabled, 'tags')
	call add(g:pathogen_disabled, 'tlib_vim')
	call add(g:pathogen_disabled, 'vim-addon-mw-utils')
	call add(g:pathogen_disabled, 'vim-argumentative')
	call add(g:pathogen_disabled, 'vimbufsync')
	call add(g:pathogen_disabled, 'vim-cljrefactor')
	call add(g:pathogen_disabled, 'vim-clojure-static')
	call add(g:pathogen_disabled, 'vim-commentary')
	call add(g:pathogen_disabled, 'vim-dispatch')
	call add(g:pathogen_disabled, 'vim-fireplace')
	call add(g:pathogen_disabled, 'vim-fugitive')
	call add(g:pathogen_disabled, 'vim-gitgutter')
	call add(g:pathogen_disabled, 'vim-glsl')
	call add(g:pathogen_disabled, 'vim-gutentags')
	call add(g:pathogen_disabled, 'vim-highlighturl')
	call add(g:pathogen_disabled, 'vim-indent-object')
	call add(g:pathogen_disabled, 'vim-jade')
	call add(g:pathogen_disabled, 'vim-latex')
	call add(g:pathogen_disabled, 'vim-leiningen')
	call add(g:pathogen_disabled, 'vim-linux-coding-style')
	call add(g:pathogen_disabled, 'vim-lion')
	call add(g:pathogen_disabled, 'vim-lsc')
	call add(g:pathogen_disabled, 'vim-minizinc')
	call add(g:pathogen_disabled, 'vim-modelica')
	call add(g:pathogen_disabled, 'vim-monochrome')
	call add(g:pathogen_disabled, 'vim-ocl')
	call add(g:pathogen_disabled, 'vim-pandoc')
	call add(g:pathogen_disabled, 'vim-pathogen')
	call add(g:pathogen_disabled, 'vim-projectionist')
	call add(g:pathogen_disabled, 'vim-racket')
	call add(g:pathogen_disabled, 'vim-repeat')
	call add(g:pathogen_disabled, 'Vim-R-plugin')
	call add(g:pathogen_disabled, 'vim-rtags')
	call add(g:pathogen_disabled, 'vim-sendtoterm')
	call add(g:pathogen_disabled, 'vim-sexp')
	call add(g:pathogen_disabled, 'vim-sexp-mappings-for-regular-people')
	call add(g:pathogen_disabled, 'vim-slamhound')
	call add(g:pathogen_disabled, 'vim-snippets')
	" call add(g:pathogen_disabled, 'vim-surround')
	call add(g:pathogen_disabled, 'YCM-Generator')
	call add(g:pathogen_disabled, 'YouCompleteMe')
	" disable eclim
	let g:EclimDisabled = 1
endif

runtime bundle/vim-pathogen/autoload/pathogen.vim
call pathogen#infect() 
call pathogen#helptags()

filetype plugin indent on
syntax on

au BufRead,BufNewFile *.fs set filetype=forth
au BufRead,BufNewFile *.Rtex set filetype=rnoweb
au BufRead,BufNewFile *.jrag set filetype=java
au BufRead,BufNewFile *.jadd set filetype=java
au BufRead,BufNewFile *.tt set filetype=java

autocmd FileType python BracelessEnable +indent +fold

augroup CursorLine
	" Highlight the line under the cursor in the 
	" active window
	" from https://vim.fandom.com/wiki/Highlight_current_line
	au!
	au VimEnter,WinEnter,BufWinEnter * setlocal cursorline
	au WinLeave * setlocal nocursorline
augroup END

au BufRead,BufNewFile *.pl set filetype=perl

" autosave when buffer is modified
" autocmd BufRead * autocmd TextChanged,TextChangedI <buffer> silent write
" autosave every updatetime milliseconds
function AutoSave()
	if !&readonly 
		if &buftype == ""
			silent checktime 
			" comment this out to only autodetect updates to the underlying file
			silent write 
		endif 
	endif
endfunction 
autocmd BufRead * autocmd CursorHold <buffer> :call AutoSave()
" set updatetime to 1 second instead of the default 4 seconds
set updatetime=1000

" UltiSnips triggering. from https://github.com/ycm-core/YouCompleteMe/issues/2032
let g:UltiSnipsExpandTrigger = '<C-j>'
let g:UltiSnipsJumpForwardTrigger = '<C-j>'
let g:UltiSnipsJumpBackwardTrigger = '<C-k>'

colorscheme default
" highlight the line under the cursor using dark grey background, and no underline
hi CursorLine   cterm=NONE ctermbg=95 ctermfg=NONE

map <leader>c :Gca<CR>
map <leader>d :Gdf<CR>


command Vrc edit $MYVIMRC

" edit filetype specific settings
command Ftplugin execute 'edit $HOME/.vim/ftplugin/'. &filetype . '.vim'

command Ecolors edit ~/.vim/bundle/vim-monochrome/colors/monochrome.vim
" lists all the active syntax highlighting groups in their own color (from :help hi)
command Hitest source $VIMRUNTIME/syntax/hitest.vim

command -nargs=1 Mann edit $HOME/man/<args>.txt

" insert reference to the current position on the form filename:linenumber: in the
" paste buffer
map <Leader>l :s+$+\= "\n" . expand('%') . ":" . line('.') . ":"+ <bar> norm ddk<CR>

map <leader>n :new <bar> set buftype=nofile<CR>

map <leader>f <c-w>F

" execute current line by piping to bash
nmap <Leader>x !!bash<CR>
" execute current line interactively in a new :terminal window.
" using this with the cursor on a blank line opens up a new terminal.
" get to the next blank line fast with '}'
" useful for interactive programs (i.e. that require tty)
nmap <localleader>x :terminal <c-r><c-l><CR>

" execute current selection by piping to bash
vmap <Leader>x !bash<CR>

" the :Man command opens up the manpage in a new split
runtime ftplugin/man.vim
set keywordprg=:Man

runtime local/*.vim
